name: society_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  device_preview: ^1.2.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  lottie: ^3.1.3
  another_flushbar: ^1.12.30
  provider: ^6.1.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  app_settings: ^5.1.1
  firebase_analytics: ^11.3.3
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  get: ^4.6.6
  path_provider: ^2.1.5
  dropdown_search: ^5.0.3
  flutter_bloc: ^8.1.6
  flutter_login: ^5.0.0
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  pretty_dio_logger: ^1.4.0
  search_page: ^2.3.0
  dio: ^5.7.0
  dash_chat_2: ^0.0.21
  equatable: ^2.0.7
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/img/dashboard/notification/
    - assets/img/dashboard/Amenity_booking/
    - assets/img/dashboard/directory/
    - assets/img/dashboard/gallery/
    - assets/img/dashboard/labour/
    - assets/img/dashboard/medical_module/
    - assets/img/dashboard/rent_sale/
    - assets/img/dashboard/sale_household/
    - assets/img/dashboard/security_service/
    - assets/img/dashboard/shop_module/
    - assets/img/dashboard/tiffin_management/
    - assets/img/gs/
    - assets/img/bp/
    - assets/img/super/
    - assets/img/login_page.png
    - assets/img/more/
    
    - assets/navbar/
    - assets/animation/
    


    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
