// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4LpBKFUnCGsx-Zy-opaRIQxwX6tO220A',
    appId: '1:237046293734:web:46942b3dbce307bbbd0727',
    messagingSenderId: '237046293734',
    projectId: 'societyclub-5a9a4',
    authDomain: 'societyclub-5a9a4.firebaseapp.com',
    storageBucket: 'societyclub-5a9a4.firebasestorage.app',
    measurementId: 'G-41NP066P4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHyd7siJYo04rsG_tA1LbptONJUbGZ1vw',
    appId: '1:237046293734:android:fa3a1bb0fd52dd47bd0727',
    messagingSenderId: '237046293734',
    projectId: 'societyclub-5a9a4',
    storageBucket: 'societyclub-5a9a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6D0vZe3YzoR2J_dT7jNc6070bagvpmY',
    appId: '1:237046293734:ios:d235113e21a25703bd0727',
    messagingSenderId: '237046293734',
    projectId: 'societyclub-5a9a4',
    storageBucket: 'societyclub-5a9a4.firebasestorage.app',
    iosBundleId: 'com.example.societyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6D0vZe3YzoR2J_dT7jNc6070bagvpmY',
    appId: '1:237046293734:ios:d235113e21a25703bd0727',
    messagingSenderId: '237046293734',
    projectId: 'societyclub-5a9a4',
    storageBucket: 'societyclub-5a9a4.firebasestorage.app',
    iosBundleId: 'com.example.societyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4LpBKFUnCGsx-Zy-opaRIQxwX6tO220A',
    appId: '1:237046293734:web:afb2795a93aa9879bd0727',
    messagingSenderId: '237046293734',
    projectId: 'societyclub-5a9a4',
    authDomain: 'societyclub-5a9a4.firebaseapp.com',
    storageBucket: 'societyclub-5a9a4.firebasestorage.app',
    measurementId: 'G-CDZXFFJMKX',
  );
}
